version: "3"
services:
  web:
    build:
      context: .
      dockerfile: web.docker
    volumes:
      - ./src:/var/www
    ports:
      - "8080:80"
    links:
      - app

  app:
    build:
      context: .
      dockerfile: app.docker
    volumes:
      - ./src:/var/www
    links:
      - database
      - cache
    environment:
      - "DB_HOST=database"
      - "DB_PORT=3306"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=cache"

  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=dockerApp"
    ports:
      - "33061:3306"

  cache:
    image: redis:3.0
    ports:
      - "63791:6379"
